google/webkit_inspection_protocol.dart

- lib/src/console.dart
- lib/src/debugger.dart
- lib/src/dom.dart
- lib/src/page.dart
- lib/webkit_inspection_protocol.dart
- pubspec.yaml
- Move each domain into a separate part.
- Delete some unused/unfinished code.
- Simplify code by removing _Event and WipObject classes.
- Change some code to use async/await.
- Add generic public onNotification stream and sendCommand method to WipConnection to support planned debug port multiplexor.
> Refactor and cleanup of webkit_inspection_protocol.dart

- bin/multiplex.dart
- lib/forwarder.dart
- pubspec.yaml
This is useful when using the multiplexor to debug a web app while running a webdriver test against it, as chromedriver will automatically resume if a paused event is received.
Change bin/multiplex model_dom option to false by default.
> Change forwarder to not send paused events unless a breakpoint event has been sent.

- lib/multiplex.dart
Chrome 45 uses /devtools/inspector.html instead of /devtools/devtools.html.
e.g. localhost:9222/json
{
"description": "",
"devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/57DD6140-1AE2-482A-87F2-6656522AB965",
"faviconUrl": "https://www.google.com/favicon.ico",
"id": "57DD6140-1AE2-482A-87F2-6656522AB965",
"title": "New Tab",
"type": "page",
"url": "http://localhost:9222/json",
"webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/57DD6140-1AE2-482A-87F2-6656522AB965"
}
> Uses inspector.html instead of devtools.html

- changelog.md
- lib/src/console.dart
- lib/src/debugger.dart
- lib/src/dom.dart
- lib/src/log.dart
- lib/src/page.dart
- lib/src/runtime.dart
- lib/webkit_inspection_protocol.dart
- pubspec.yaml
- test/console_test.dart
- Expose the `runtime` domain.
- Expose the `log` domain.
- Deprecated the `console` domain.
- Fix a bug in `Page.reload()`.
- Remove the use of parts.
rev to `0.3.0`
> expose log and runtime domain; deprecate console

- lib/forwarder.dart
`dartanalyzer lib/` shows one uses_dynamic_as_bottom error. This fixes that.
> Fix uses_dynamic_as_bottom error

- analysis_options.yaml
- changelog.md
- lib/src/runtime.dart
- pubspec.yaml
Fixes https://github.com/google/webkit_inspection_protocol.dart/issues/41
I did this as a breaking change since it technically is breaking... an explicit cast may now be required.
cc @devoncarew
> change the RemoteObject.value return type to Object

- analysis_options.yaml
- bin/multiplex.dart
- changelog.md
- lib/forwarder.dart
- lib/multiplex.dart
- lib/src/console.dart
- lib/src/debugger.dart
- lib/src/dom.dart
- lib/src/log.dart
- lib/src/page.dart
- lib/src/runtime.dart
- lib/src/target.dart
- lib/webkit_inspection_protocol.dart
- pubspec.yaml
- test/test_setup.dart
Fixes https://github.com/google/webkit_inspection_protocol.dart/issues/44
I can separate out that change if you want (the bug fix), but imo its worth disabling the implicit casts entirely since they are not safe (as evidenced by the issue).
The only api change I believe is I changed `WipForwarder` to take a `Stream<String>` explicitly, instead of a `Stream<dynamic>`. I could change that to an internal cast but I think its better to express the required type explicitly.
> turn on implicit casts, fix Page.reload

- changelog.md
- lib/webkit_inspection_protocol.dart
- pubspec.yaml
A recent change to HttpClientResponse updated it to
implement `Stream<Uint8List>` rather than `Stream<List<int>>`.
This forwards-compatible change correspondingly casts
the stream to `List<int>`.
https://github.com/dart-lang/sdk/issues/36900
> Fix for HttpClientResponse SDK breaking change

- changelog.md
- lib/src/debugger.dart
- pubspec.yaml
Use `type` field to get the type of `WipScope` instead of `scope`, which is not set in the remote object returned by chrome.
This closes #49
> Use correct field when reading WipScope

- .travis.yml
- pubspec.yaml
- test/console_test.dart
- test/test_setup.dart
- tool/travis.sh
- Add infra to install and spin up CHROMEDRIVER
- Remove tests that no longer work since the console protocol has changed / is deprecated
Closes https://github.com/google/webkit_inspection_protocol.dart/issues/24
> Re-Enable Tests

- test/dom_model_test.dart
- skip a filing test (tracking re-enabling it in https://github.com/google/webkit_inspection_protocol.dart/issues/52)
> skip a failing test

- changelog.md
- lib/src/debugger.dart
- pubspec.yaml
Solving the issue https://github.com/dart-lang/sdk/issues/40774 requires that scope name is exposed on WipScope API, so add a field to do so.
> Expose name on WipScope

- changelog.md
- lib/src/runtime.dart
- lib/webkit_inspection_protocol.dart
- pubspec.yaml
- Add `onSend` and `onReceive` in `WipConnection` 
- Expose `onExecutionContextCreated`, `onExecutionContextDestroyed`,
and `onExecutionContextsCleared` on WipRuntime
- rev to `0.6.0` in prep for publishing
> add APIs to view WIP traffic

- changelog.md
- lib/src/console.dart
- lib/src/debugger.dart
- lib/src/dom.dart
- lib/src/log.dart
- lib/src/runtime.dart
- lib/webkit_inspection_protocol.dart
- pubspec.yaml
- test/data/runtime_test.html
- test/dom_model_test.dart
- test/runtime_test.dart
- test/test_setup.dart
- Normalized all objects to expose a `json` field for raw access to the protocol information.
- Exposed Runtime.getProperties, Runtime.getHeapUsage, and Runtime.getIsolateId
- Exposed `DebuggerPausedEvent.hitBreakpoints` and `DebuggerPausedEvent.asyncStackTrace`
- Exposed `WipCallFrame.returnValue`
- Removed `WrappedWipEvent` (in favor of just using `WipEvent`)
- Removed `WipRemoteObject` (in favor of just using `RemoteObject`)
- rev to the next major version (`0.7.0`)
> expose more methods; change API; rev version

- changelog.md
- lib/src/debugger.dart
- lib/src/runtime.dart
- pubspec.yaml
expose more fields related to async frames:
- Exposed `Debugger.setAsyncCallStackDepth`
- Exposed `StackTrace.parent`
- rev to `0.7.1` in prep for publishing
> expose more fields related to async frames

- changelog.md
- lib/src/runtime.dart
- pubspec.yaml
- fix a bug in StackTrace.parent
- rev to `0.7.2`
> fix a bug in StackTrace.parent

- analysis_options.yaml
- changelog.md
- lib/src/debugger.dart
- pubspec.yaml
This is technically a breaking change but given that the old behavior is invalid we want consumers to catch this error. The somewhat related lint did not catch this specific issue but is good to have anyway.
> Fix type issue with GlobalObjectClearedEvents

- CHANGELOG.md
- lib/webkit_inspection_protocol.dart
- pubspec.yaml
- Have `ChromeConnection.getTabs` return better exceptions where there's a failure setting up the Chrome connection (#85).
- Introduce a new, optional `retryFor` parameter to `ChromeConnection.getTabs`. This will re-try failed connections for a period of time; it can be useful to mitigate some intermittent connection issues very early in Chrome's startup.
- fix https://github.com/google/webkit_inspection_protocol.dart/issues/85
> improve failure modes of ChromeConnection.getTabs

- CHANGELOG.md
- lib/webkit_inspection_protocol.dart
- pubspec.yaml
- test/test_setup.dart
- introduce an optional `onError` parameter when setting up a WipConnection
- potentially adddress https://github.com/google/webkit_inspection_protocol.dart/issues/86
> introduce an optional 'onError' parameter

- .github/dependabot.yaml
- .github/workflows/no-response.yml
- .github/workflows/publish.yaml
This PR contains changes created by the blast repo tool.
- `auto-publish`
- `dependabot`
- `github-actions`
- `no-response`
> blast repo changes: auto-publish, dependabot, github-actions, no-response

- .github/workflows/build.yaml
- CHANGELOG.md
- analysis_options.yaml
- example/multiplex.dart
- example/multiplex_impl.dart
- lib/dom_model.dart
- lib/forwarder.dart
- lib/src/console.dart
- lib/src/debugger.dart
- lib/src/dom.dart
- lib/src/log.dart
- lib/src/page.dart
- lib/src/runtime.dart
- lib/src/target.dart
- lib/webkit_inspection_protocol.dart
- pubspec.yaml
- test/console_test.dart
- test/debugger_test.dart
- test/dom_model_test.dart
- test/runtime_test.dart
- test/test_setup.dart
> Update min SDK and a number of lints
