google/webkit_inspection_protocol.dart

pubspec.yaml, tool/travis.sh
- use tuneup to validate the code
=> use tuneup to validate the code

bin/multiplex.dart, lib/forwarder.dart, lib/src/debugger.dart, pubspec.yaml
Allows multiple WIP clients to connect to a single chrome tab.
=> Add multiplex binary

.travis.yml, lib/src/console.dart, lib/webkit_inspection_protocol.dart, pubspec.yaml, test/console_test.dart, test/data/console_test.html, test/test_setup.dart, tool/travis.sh
=> Add tests for console domain.

.travis.yml, test/console_test.dart, test/data/console_test.html, test/test_setup.dart, tool/travis.sh
- general improvements to console_test
- run tests on both dev and stable
- ensure tests are run single-threaded
=> Refactor tests to make them more reliable

analysis_options.yaml, lib/dom_model.dart, lib/forwarder.dart, lib/src/dom.dart, lib/webkit_inspection_protocol.dart
- add an analysis options file to enable strong mode
- fix strong mode errors
- run dartfmt on the source
@grouma, do you mind reviewing?
=> make package:webkit_inspection_protocol strong

changelog.md, pubspec.yaml
- rev to 0.3.4
- fix https://github.com/google/webkit_inspection_protocol.dart/issues/34
@grouma
=> rev to 0.3.4

analysis_options.yaml, changelog.md, example/multiplex.dart, example/multiplex_impl.dart, lib/dom_model.dart, lib/src/debugger.dart, lib/webkit_inspection_protocol.dart, pubspec.yaml, readme.md, test/console_test.dart, test/dom_model_test.dart
- remove unnecessary deps
- removed the bin/multiplex.dart binary to the example/ directory
- remove dependencies on `package:args`, package:shelf`, and `package:shelf_web_socket`
- rev'd to a new major version: `0.5.0`
- addressed some lints
=> remove unnecessary deps

analysis_options.yaml, changelog.md, lib/src/console.dart, lib/src/debugger.dart, lib/src/log.dart, lib/src/page.dart, lib/src/runtime.dart, lib/src/target.dart, lib/webkit_inspection_protocol.dart, pubspec.yaml, test/console_test.dart, test/data/debugger_test.html, test/debugger_test.dart, test/test_setup.dart
Add several debugger and runtime methods:
- add `Runtime.evaluate`
- add `Debugger.setBreakpoint`
- add `Debugger.removeBreakpoint`
- add `Debugger.evaluateOnCallFrame`
- add `Debugger.getPossibleBreakpoints`
- rev to `0.5.1`
=> add several debugger and runtime methods

changelog.md, lib/src/runtime.dart, lib/webkit_inspection_protocol.dart, pubspec.yaml
- have `ExceptionDetails` and `WipError` implement `Exception`
- add `code` and `message` getters to `WipError`
=> rev to publish 0.5.2

CHANGELOG.md, analysis_options.yaml, example/multiplex.dart, example/multiplex_impl.dart, lib/dom_model.dart, lib/forwarder.dart, lib/src/console.dart, lib/src/debugger.dart, lib/src/dom.dart, lib/src/log.dart, lib/src/runtime.dart, lib/webkit_inspection_protocol.dart, pubspec.yaml, test/console_test.dart, test/debugger_test.dart, test/dom_model_test.dart, test/runtime_test.dart, test/test_setup.dart
- use `package:lints` for analysis
- populate the pubspec `repository` field
=> Use package lints

CHANGELOG.md, analysis_options.yaml, lib/forwarder.dart, lib/src/dom.dart, lib/webkit_inspection_protocol.dart, test/console_test.dart
- enable the avoid_dynamic_calls lint
- fix https://github.com/google/webkit_inspection_protocol.dart/issues/71
=> enable the avoid_dynamic_calls lint

.github/workflows/build.yaml
=> run tests in github actions

.github/dependabot.yaml
=> configure dependabot

.github/workflows/build.yaml
- Use more specific versions in the github action file
=> Use more specific versions in the github action file

.github/workflows/build.yaml
- depend on actions/checkout w/ a major version dep
=> depend on actions/checkout w/ a major version dep

CHANGELOG.md, example/multiplex_impl.dart, lib/src/runtime.dart, lib/webkit_inspection_protocol.dart, pubspec.yaml, test/test_setup.dart
=> upgrade to lints 2.0.0

CHANGELOG.md, pubspec.yaml
=> prep to publish 1.1.0

.github/workflows/build.yaml, test/test_setup.dart
- update references to the older branch name
=> update references to the older branch name

.github/workflows/publish.yaml
=> add publishing automation

.github/workflows/publish.yaml, CHANGELOG.md, lib/src/runtime.dart, pubspec.yaml
- fix nullability of some type annotations
- fix https://github.com/google/webkit_inspection_protocol.dart/issues/104
=> fix nullability of some type annotations
